[package]
name = "pigeon-registry"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
pigeon-util     = { workspace = true }
pigeon-data     = { workspace = true }
pigeon-nbt      = { workspace = true }
pigeon-codecs   = { workspace = true }
indexmap        = { workspace = true }
thiserror       = { workspace = true }
parking_lot     = { workspace = true }
bytes           = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
